### ISSUE TITLE
Deployment of csar fails when adding a testing policy 

### ISSUE THREAD

**Issue by AlexSpart** [radon-h2020/radon-ctt#91]
I am experience an unexpected failure in deployment if I add a testing policy in my model.
This error occurs when i try to deploy normally the csar without invoking any CTT testing.

The error i get is the following: `_definitions/steIgeneral__cloudstash.tosca:996:5: Expected map.`
The policy in the tosca service template is defined as following: 
`policies:
    - Https_EndpointTest_policy:
        type: radon.policies.testing.HttpEndpointTest
        properties:
          path: "/"
          hostname: "cloudstash.io"
          method: "GET"
          port: "443"
          expected_status: "200"
          ti_blueprint: "radon.blueprints.testing.DeploymentTestAgentEC2"
          use_https: "true"
          test_id: "http_endpoint_test_1"
        targets: [ AwsApiGateway_0 ]`

Any idea what might be the issue?

**Comment by duelle** [comment]
As discussed in person, this seems to be an issue due to updates in the particles that have not been included in a current release of xOpera.
See:
https://github.com/radon-h2020/radon-gmt/issues/47
https://github.com/xlab-si/xopera-opera/issues/115
If you agree @AlexSpart, I'd close this issue here as this seems to be fixed once the next opera release is published.

**Comment by AlexSpart** [comment]
The dev version of Opera solved this issue so you can close it. 
Thanks for addressing the solution to this with me.
